![title](https://th.bing.com/th/id/OIP.ri4aG5v3o264bCjLF4hZ9gHaBe?rs=1&pid=ImgDetMain)

## Introduction to tensors

- Tensors are the fundamental building block of machine learning. Their job is to represent data in a numerical way.

- A ```torch.Tensor``` is a multi-dimensional matrix containing elements of a single data type.



In [6]:
# importing torch
import torch

In [8]:
# checking pytorch version
print(torch.__version__)

2.1.0+cu118


 ### Scalar
 - A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [4]:
# scalar
scalar = torch.tensor(5)
print(scalar)

tensor(5)


```tensor(5) ``` means although scalar is a single number, it's of type ```torch.Tensor```.

### ndim
We can check the dimensions of a tensor using the ```ndim attribute```.


In [7]:
scalar.ndim

0

### scalar.item()
```scalar.item()``` converts tensor back to integer **(only works with one-element tensors).**

In [10]:
scalar.item()

5

## Vector
- A vector is a single dimension tensor but can contain many numbers.
- Eg: a vector ```[3, 2]``` to describe ```[bedrooms, bathrooms]```

In [11]:
vector = torch.tensor([3,2])
vector

tensor([3, 2])

In [12]:
vector.shape

torch.Size([2])

```torch.Size([2])``` which means our vector has a shape of ```[2]```. This is because of the two elements we placed inside the square brackets ```([7, 7])```.

In [13]:
vector.ndim

1

Dimensionality is 1 means it is 1-d vector or it has **one-pair of [] (square bracket).** 

## MATRIX

In [16]:
MATRIX = torch.tensor([[3,2],[4,5]])
MATRIX

tensor([[3, 2],
        [4, 5]])

In [17]:
MATRIX.shape

torch.Size([2, 2])

```torch.Size([2, 2])``` means that the matrix is of shape ```2x2```

In [18]:
MATRIX.ndim

2

Dimension is ```2``` as it has 2 pairs of square brackets.

### Getting First Row

In [20]:
MATRIX[0]

tensor([3, 2])

### Getting Second Row

In [21]:
MATRIX[1]

tensor([4, 5])

### Getting First Column

In [25]:
MATRIX[:,0]

tensor([3, 4])

### Getting Second Column

In [22]:
MATRIX[:,1]

tensor([2, 5])

## Tensor

In [28]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9, 5],
                        [2, 4, 5, 7]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 5],
         [2, 4, 5, 7]]])

In [30]:
TENSOR.ndim

3

In [46]:
TENSOR.shape

torch.Size([1, 3, 4])

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png" alt="title" width="600px" />


In [31]:
# Grabbing specific column
TENSOR[:,:,1]

tensor([[2, 6, 4]])

In [39]:
# Grabbing specific element
TENSOR[0,2,3]

tensor(7)

In [44]:
# Grabbing tensor subset
TENSOR[0,1:,1:3]

tensor([[6, 9],
        [4, 5]])

# In summary
<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" alt="title" width="400px" style="display: block; margin: auto;"/>
