![title](https://meterpreter.org/wp-content/uploads/2017/12/pytorch-logo-dark-1024x205.png)

In [1]:
import torch

# Random

### TORCH.RAND
- Returns a tensor filled with random numbers from a uniform distribution on the interval ```[0,1)```
- The shape of the tensor is defined by the variable argument size

In [4]:
torch.rand(3)

tensor([0.8117, 0.8933, 0.3380])

In [3]:
torch.rand(3,4)

tensor([[0.5010, 0.5570, 0.4828, 0.0767],
        [0.5109, 0.2079, 0.6466, 0.9725],
        [0.1339, 0.6444, 0.7903, 0.2327]])

In [5]:
torch.rand(3,4,3)

tensor([[[0.0878, 0.5242, 0.7555],
         [0.0929, 0.0045, 0.5167],
         [0.9656, 0.5219, 0.7033],
         [0.9621, 0.9617, 0.2800]],

        [[0.9081, 0.3665, 0.7650],
         [0.8317, 0.2256, 0.0292],
         [0.9550, 0.1382, 0.6592],
         [0.7973, 0.8502, 0.5497]],

        [[0.0732, 0.4248, 0.4523],
         [0.8943, 0.7155, 0.0954],
         [0.3898, 0.7183, 0.5399],
         [0.2009, 0.2512, 0.9350]]])

#### Create a random tensor of size (224, 224, 3) - (height, width, channel)

In [6]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [10]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Range of tensors

### TORCH.ARANGE
```torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor```

- Returns a 1-D tensor of size ```⌈(end−start)/step⌉``` with values from the interval ```[start, end)``` taken with common difference step beginning from start.

- OUT<sub>i+1</sub> = OUT<sub>i</sub> + step


##### **Parameters**
- **start (Number)** – the starting value for the set of points. Default: 0.

- **end (Number)** – the ending value for the set of points

- **step (Number)** – the gap between each pair of adjacent points. Default: 1.

In [12]:
torch.arange(0,11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
torch.arange(0,11,2)

tensor([ 0,  2,  4,  6,  8, 10])

In [17]:
torch.arange(0.5,1043.6,78.549)

tensor([5.0000e-01, 7.9049e+01, 1.5760e+02, 2.3615e+02, 3.1470e+02, 3.9324e+02,
        4.7179e+02, 5.5034e+02, 6.2889e+02, 7.0744e+02, 7.8599e+02, 8.6454e+02,
        9.4309e+02, 1.0216e+03])

### TORCH.ZEROS_LIKE
- Returns a tensor filled with the scalar value 0, with the same size as ```input```. 

In [19]:
input = torch.empty(2,3)
torch.zeros_like(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
input = torch.arange(2,10)
torch.zeros_like(input)

tensor([0, 0, 0, 0, 0, 0, 0, 0])

### TORCH.ONES_LIKE
- Creates a new tensor with the same shape as the input tensor, filled with ones.

In [27]:
torch.ones_like(input)

tensor([1, 1, 1, 1, 1, 1, 1, 1])

### TORCH.FULL_LIKE
- Creates a new tensor with the same shape as the input tensor, filled with a specified value.



In [31]:
torch.full_like(input, fill_value=5)

tensor([5, 5, 5, 5, 5, 5, 5, 5])

### TORCH.RAND_LIKE
- Creates a new tensor with the same shape as the input tensor, with values drawn from a uniform distribution between 0 and 1.

In [33]:
torch.rand_like(input,dtype=torch.float)

tensor([0.7438, 0.9077, 0.8117, 0.9765, 0.4578, 0.5805, 0.2121, 0.5600])

### TORCH.RANDN_LIKE
- Creates a new tensor with the same shape as the input tensor, with values drawn from a standard normal distribution.

In [34]:
torch.randn_like(input,dtype=torch.float)

tensor([ 0.3012, -1.4129,  0.2589,  1.4966, -1.3740,  0.4260, -0.3777,  0.6407])

### TORCH.EMPTY_LIKE
- Creates a new tensor with the same shape as the input tensor, without initializing the values. This is typically faster but the values will be whatever happens to be in memory.



In [37]:
torch.empty_like(input)

tensor([5706002664256,             3,             4,             5,
                    6,             7,             8,             9])