![title](https://meterpreter.org/wp-content/uploads/2017/12/pytorch-logo-dark-1024x205.png)

# Tensor Manipulation
1. Addition
2. Subtraction
3. Multiplication (Element-wise)
4. Division
5. Matrix Multiplication

In [1]:
import torch

In [3]:
T = torch.tensor([1,2,3])
T

tensor([1, 2, 3])

In [4]:
T + 10

tensor([11, 12, 13])

In [5]:
T - 10

tensor([-9, -8, -7])

In [6]:
T * 10

tensor([10, 20, 30])

In [7]:
T / 10

tensor([0.1000, 0.2000, 0.3000])

### PyTorch in-built function

**1. torch.add()**

In [12]:
torch.add(T, 10)

tensor([11, 12, 13])

**2. torch.sub() and torch.subtract()**

In [13]:
torch.sub(T, 10)

tensor([-9, -8, -7])

In [14]:
torch.subtract(T, 10)

tensor([-9, -8, -7])

**3. torch.mul() and torch.multiply()**

In [16]:
torch.mul(T, 10)

tensor([10, 20, 30])

In [17]:
torch.multiply(T, 10)

tensor([10, 20, 30])

**4. torch.div() and torch.divide()**

In [18]:
torch.div(T, 10)

tensor([0.1000, 0.2000, 0.3000])

In [19]:
torch.divide(T, 10)

tensor([0.1000, 0.2000, 0.3000])

**5. Matrix Multiplication**

The main two rules for matrix multiplication to remember are:

The **inner dimensions** must match:
- ```(3, 2) @ (3, 2)``` won't work
- ```(2, 3) @ (3, 2)``` will work
- ```(3, 2) @ (2, 3)``` will work

The resulting matrix has the shape of the **outer dimensions**:
- ```(2, 3) @ (3, 2)``` -> (2, 2)
- ```(3, 2) @ (2, 3)``` -> (3, 3)

In [20]:
T

tensor([1, 2, 3])

In [21]:
torch.matmul(T, T)

tensor(14)

In [24]:
%%time
value = 0
for i in range(len(T)):
    value += T[i]*T[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 11 ms


In [25]:
%%time
print(torch.matmul(T, T))

tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


**```torch.matmul()```** is much much faster than normal loop based matrix calculation

In [35]:
%%time
T @ T

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

**`@`** is same as **```torch.matmul()```**

### One of the most common errors in deep learning (shape errors)


In [37]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).
- `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0 and dim1` are the dimensions to be swapped.

- `tensor.T` - where tensor is the desired tensor to transpose.

In [41]:
print(tensor_A)
print(tensor_B)
print('shapes are', tensor_A.shape, tensor_B.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
shapes are torch.Size([3, 2]) torch.Size([3, 2])


In [42]:
print(tensor_A)
print(tensor_B.T)
print('shapes are', tensor_A.shape, tensor_B.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
shapes are torch.Size([3, 2]) torch.Size([3, 2])


In [43]:
torch.matmul(tensor_A, tensor_B.T) # (this will work)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [44]:
torch.matmul(tensor_A.T, tensor_B) # (this will work)

tensor([[ 76., 103.],
        [100., 136.]])

You can also use `torch.mm()` which is a short for `torch.matmul()`.

In [45]:
torch.mm(tensor_A.T, tensor_B) # (this will work)

tensor([[ 76., 103.],
        [100., 136.]])

Neural networks are full of matrix multiplications and dot products.

The `torch.nn.Linear()` module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

y = x **⋅** A <sup>T</sup> + b

Where:

- **x** is the input to the layer (deep learning is a stack of layers like **torch.nn.Linear()** and others on top of each other).

- **A** is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the **"T"**, that's because the weights matrix gets transposed).

	- **Note**: You might also often see **W** or another letter like **X** used to showcase the weights matrix.

- **b** is the bias term used to slightly offset the weights and inputs.

- **y** is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like `y=mx+b` in high school or elsewhere), and can be used to draw a straight line!

In [54]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
