![title](https://meterpreter.org/wp-content/uploads/2017/12/pytorch-logo-dark-1024x205.png)

# TENSOR AGGREGATION
Tensor aggregation operations reduce a tensor to a smaller size or a single value by applying a specific operation.

Here's a list of common tensor aggregation operations:
- Sum
- Mean
- Product
- Min
- Max
- Standard Deviation
- Variance
- Argmax
- Argmin
- Norm
- Cumulative Sum
- Cumulative Product

Additional or specialized aggregation functions: 
- Median
- Any
- All
- Unique
- Top k
- Sort
- Quantile
- Mode
- Softmax
- LogSumExp:

In [1]:
import torch

In [3]:
t = torch.arange(10,101,10)
t

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### 1. Sum
- **Explanation**: Calculates the sum of all elements in the tensor.
- **PyTorch Code**: `torch.sum(tensor)` or `tensor.sum()`

In [5]:
# t.sum() is same as torch.sum(t)
t.sum()
torch.sum(t)

tensor(550)

### 2. Mean

- **Explanation**: Computes the mean of all elements in the tensor.
- **PyTorch Code**: `torch.mean(tensor)` or `t.mean()`

In [7]:
t.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

**The error is due to dtype unsupport. It can be fixed by changing dtype**

In [10]:
t.dtype

torch.int64

**int64 is not supported with tensor.mean()**

In [14]:
t.type(torch.float32)

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
t.type(torch.float32).mean()

tensor(55.)

### 3. Product:

- **Explanation**: Calculates the product of all elements in the tensor.
- **PyTorch Code**: `torch.prod(tensor)`

In [16]:
t.prod()

tensor(36288000000000000)

### 4. Min:

- **Explanation**: Identifies the minimum value in the tensor.
- **PyTorch Code**: `torch.min(tensor)`

In [17]:
t.min()

tensor(10)

### 5. Max:

- **Explanation**: Identifies the maximum value in the tensor.
- **PyTorch Code**: `torch.max(tensor)`

In [19]:
t.max()

tensor(100)

### 6. Standard Deviation:

- **Explanation**: Computes the standard deviation of elements in the tensor.
- **PyTorch Code**: `torch.std(tensor)`

In [22]:
t.std()

RuntimeError: std and var only support floating point and complex dtypes

In [23]:
t.type(torch.float32).std()

tensor(30.2765)

### 7. Variance:

- **Explanation**: Calculates the variance of elements in the tensor.
- **PyTorch Code**: `torch.var(tensor)`

In [24]:
t.var()

RuntimeError: std and var only support floating point and complex dtypes

In [25]:
t.type(torch.float32).var()

tensor(916.6667)

### 8. Argmax:

- **Explanation**: Returns the index of the maximum value in a tensor along a specified axis.
- **PyTorch Code**: `torch.argmax(input=tensor, dim=axis)`

In [26]:
t.argmax()

tensor(9)

In [29]:
# actual element at 9th index
print('Actual tensor', t)
print(t[9])

Actual tensor tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
tensor(100)


### 9. Argmin:

- **Explanation**: Returns the index of the minimum value in a tensor along a specified axis.
- **PyTorch Code**: `torch.argmin(input=tensor, dim=axis)`

In [30]:
t.argmin()

tensor(0)

In [31]:
# actual element at 0th index
print('Actual tensor', t)
print(t[0])

Actual tensor tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
tensor(10)


### 10. Norm:

- **Explanation**: Computes the norm of a tensor. The default is the Euclidean norm (L2), but you can specify other norms.
- **PyTorch Code**: `torch.norm(input=tensor, p='fro')` for Frobenius norm, replace 'fro' with the desired norm.


In [32]:
t.norm()

RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Long

In [34]:
t.type(torch.float32).norm(p="fro")

tensor(196.2142)

### 11. Cumulative Sum:

- **Explanation**: Computes the cumulative sum of the elements along a given axis.
- **PyTorch Code**: `torch.cumsum(tensor, dim=axis)`

In [36]:
t.cumsum(axis=0)

tensor([ 10,  30,  60, 100, 150, 210, 280, 360, 450, 550])

### 12. Cumulative Product:

- **Explanation**: Computes the cumulative product of the elements along a given axis.
- **PyTorch Code**: `torch.cumprod(tensor, dim=axis)`

In [38]:
t.cumprod(axis=0)

tensor([               10,               200,              6000,
                   240000,          12000000,         720000000,
              50400000000,     4032000000000,   362880000000000,
        36288000000000000])

# Additional Aggregations
### 13. Median:

- **Explanation**: Computes the median of the elements in the tensor.
- **PyTorch Code**: `torch.median(tensor)`

In [40]:
t.median()

tensor(50)

### 14. Any:

- **Explanation**: Checks if any of the elements in the tensor are True (usually for boolean tensors).
- **PyTorch Code**: `torch.any(tensor)`

In [41]:
t.any()

tensor(True)

### 15. All:

- **Explanation**: Checks if all the elements in the tensor are True (usually for boolean tensors).
- **PyTorch Code**: `torch.all(tensor)`

In [42]:
t.all()

tensor(True)

### 15. Unique:

- **Explanation**: Finds unique elements in a tensor.
- **PyTorch Code**: `torch.unique(tensor)`

In [45]:
t2 = torch.tensor([10,10,14,12,12,14,15])
t2.unique()

tensor([10, 12, 14, 15])

### 15. Top k:

- **Explanation**: Finds the k largest elements in the tensor.
- **PyTorch Code**: `torch.topk(tensor, k)`

In [46]:
t.topk(4)

torch.return_types.topk(
values=tensor([100,  90,  80,  70]),
indices=tensor([9, 8, 7, 6]))

### 16. Sort:

- **Explanation**: Sorts the elements of the tensor.
- **PyTorch Code**: `torch.sort(tensor, dim=-1)`

In [48]:
t2 = torch.tensor([10,10,14,12,12,14,15])
t2.sort()

torch.return_types.sort(
values=tensor([10, 10, 12, 12, 14, 14, 15]),
indices=tensor([0, 1, 3, 4, 2, 5, 6]))

### 17. Quantile:

- **Explanation**: Computes the quantile of a tensor.
- **PyTorch Code**: Can be calculated using `torch.quantile(input, q, dim=None, keepdim=False, *, interpolation='linear', out=None)`.

In [55]:
a = torch.randn(2, 3)
print(a)
q = torch.tensor([0.25, 0.5, 0.75])
print('quartiles: ',q)

tensor([[ 0.5633,  0.1407,  0.9724],
        [-2.2099, -0.0411, -0.4497]])
quartiles:  tensor([0.2500, 0.5000, 0.7500])


In [56]:
torch.quantile(a, q, dim=1, keepdim=True)

tensor([[[ 0.3520],
         [-1.3298]],

        [[ 0.5633],
         [-0.4497]],

        [[ 0.7678],
         [-0.2454]]])

In [58]:
a = torch.arange(4.)
a

tensor([0., 1., 2., 3.])

In [59]:
torch.quantile(a, 0.6, interpolation='linear')

tensor(1.8000)

### 18. Mode:

- **Explanation**: Computes the mode of the elements in the tensor.
- **PyTorch Code**: `torch.mode(tensor)`

In [69]:
t2 = torch.tensor([10,10,10,12,12])
t2.mode()

torch.return_types.mode(
values=tensor(10),
indices=tensor(2))