![title](https://meterpreter.org/wp-content/uploads/2017/12/pytorch-logo-dark-1024x205.png)

In [1]:
import torch

# Tensor Reshaping

Tensor reshaping is the process of changing the shape (i.e., the dimensions) of a tensor (a multi-dimensional array) without changing the underlying data. It's essential for making data compatible with various machine learning models and operations.

## Common Reshaping Operations:
- Reshape
- Flatten
- Squeeze
- Unsqueeze / Expand_dims:
- Transpose
- Permute
- Stack
- View (PyTorch specific)

# Reshape
- **Explanation**: Changes the shape of the tensor to the specified dimensions.
- **PyTorch**: `tensor.reshape(shape)`

In [6]:
t = torch.arange(1,13)
print(t)
print(t.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])


In [7]:
t.reshape(4,3)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [8]:
t.reshape(3,4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [9]:
t.reshape(6,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

In [10]:
t.reshape(2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

**Note**: `reshape(shape)` must be of multiplication of `m*n`.
In the above code, 12 can be represented as:
- 2 * 6
- 3 * 4
- 4 * 3
- 6 * 2


In [13]:
# otherwise, the following error will be seen.
t.reshape(3,2)

RuntimeError: shape '[3, 2]' is invalid for input of size 12

# View
- **Explanation**: Similar to reshape, but can only be used on contiguous tensors. If the tensor is not contiguous, you'll need to call tensor.contiguous() before tensor.view().
- **PyTorch Code**: `tensor.view(shape)`

In [16]:
z = t.view(2,6)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))

**NOTE: Changing z, changes t (overwritten). This is because they share same memory.**

In [18]:
z[:,0] = 5
print('z = ', z)
print('\nt = ', t)

z =  tensor([[ 5,  2,  3,  4,  5,  6],
        [ 5,  8,  9, 10, 11, 12]])

t =  tensor([ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12])


# Stack

In [19]:
t_stacked = torch.stack([t,t,t], dim=0)
t_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12]])

In [22]:
t_stacked = torch.vstack([t,t,t])
t_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12]])

In [23]:
t_stacked = torch.stack([t,t,t], dim=1)
t_stacked

tensor([[ 5,  5,  5],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 5,  5,  5],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12]])

In [24]:
t_stacked = torch.hstack([t,t,t])
t_stacked

tensor([ 5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12,  5,  2,  3,  4,  5,  6,
         5,  8,  9, 10, 11, 12,  5,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12])

### Table for dimension and stack 
<table>
<th>Dim</th>
<th>Stack</th>
<tr><td>0</td>
<td>vstack</td></tr>
<tr><td>1</td>
<td>hstack</td></tr>
</table>

# Squeeze
- **Explanation**: Removes dimensions of size 1 from the shape of a tensor. For example, if the tensor has a shape of (1, 28, 28), squeezing it would result in (28, 28).
- **PyTorch Code**: `tensor.squeeze()`

In [43]:
x = torch.zeros(2, 1, 2, 1, 2)
print('x = ',x.shape)
y = torch.squeeze(x)
print('y = ',y.shape)

x =  torch.Size([2, 1, 2, 1, 2])
y =  torch.Size([2, 2, 2])


In [44]:
y = torch.squeeze(x, 0)
print('y = ',y.shape)

y =  torch.Size([2, 1, 2, 1, 2])


In [45]:
y = torch.squeeze(x, 1)
print('y = ',y.shape)

y =  torch.Size([2, 2, 1, 2])


In [46]:
y = torch.squeeze(x, (1, 2, 3))
print('y = ',y.shape)

y =  torch.Size([2, 2, 2])


In [54]:
y = torch.squeeze(x, (3,4))
print('y = ',y.shape)

y =  torch.Size([2, 1, 2, 2])


# Unsqueeze
- **Explanation**: Adds a dimension of size 1 at a specified index. This is often used to prepare tensors for operations that require a specific number of dimensions.
- **PyTorch Code**: `tensor.unsqueeze(dim)`

In [71]:
p = y.unsqueeze(dim=0)
print('\n',y)
print('y-shape',y.shape)
print('\n',p)
print('p-shape',p.shape)



 tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])
y-shape torch.Size([2, 1, 2, 2])

 tensor([[[[[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]]]]])
p-shape torch.Size([1, 2, 1, 2, 2])


In [70]:
p = y.unsqueeze(dim=1)
print('\n',y)

print('y-shape',y.shape)
print('\n',p)
print('p-shape',p.shape)



 tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])
y-shape torch.Size([2, 1, 2, 2])

 tensor([[[[[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]]]]])
p-shape torch.Size([2, 1, 1, 2, 2])


In [76]:
p = y.unsqueeze(dim=2)
print('\n',y)
print('+----------')
print('y-shape',y.shape)
print('+----------')

print('\n',p)
print('+----------')

print('p-shape',p.shape)
print('+----------')



 tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])
+----------
y-shape torch.Size([2, 1, 2, 2])
+----------

 tensor([[[[[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]]]]])
+----------
p-shape torch.Size([2, 1, 1, 2, 2])
+----------


# Permute
- **Explanation**: A more general form of transpose. It changes the order of the axes in a tensor to any desired order.
- **PyTorch Code**: `tensor.permute(dims)`

In [77]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # (height, width, channel)

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0 (channel, height, width)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Transpose

- **Explanation**: Swaps two dimensions of a tensor. Often used to swap axes for certain types of processing or to match expected input shapes.
- **PyTorch Code**: `tensor.transpose(dim0, dim1)`


In [93]:
print('original\n', t)
print('\nTranspose\n', torch.transpose(t,0,1))

original
 tensor([[1, 2, 3],
        [4, 5, 6]])

Transpose
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [95]:
print('original\n', t)
print('\nTranspose\n', t.T)

original
 tensor([[1, 2, 3],
        [4, 5, 6]])

Transpose
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


>**Note** : torch.transpose() is same as tensor.T

# Flatten

- **Explanation**: Collapses all dimensions of a tensor into one, creating a 1D tensor from a multi-dimensional one.
- **PyTorch Code**: `tensor.flatten()`

In [99]:
print('original\n', t)
print('\nFlatten\n', t.flatten())

original
 tensor([[1, 2, 3],
        [4, 5, 6]])

Flatten
 tensor([1, 2, 3, 4, 5, 6])


## Applications:
* **Preparing Data**: Reshaping is used extensively in data preprocessing to prepare datasets for training neural networks.
* **Layer Output**: In neural networks, reshaping is often required when the output of one layer needs to be transformed to match the input shape expected by the next layer.
* **Feature Engineering**: Reshaping can help in creating new features from existing data.