![title](https://meterpreter.org/wp-content/uploads/2017/12/pytorch-logo-dark-1024x205.png)

In [1]:
import torch

# Reproducibility
- Reproducibility in machine learning, including in PyTorch, refers to the ability to **recreate the same results using the same model and the same data**. 

- This is crucial for validating experiments and for ensuring that models behave expectedly in production. 

- However, achieving perfect reproducibility in PyTorch (or any other deep learning framework) can be challenging due to the many factors that can introduce variability. 

# Sources of Non-Reproducibility
- **Randomness**: Most machine learning algorithms have some level of inherent randomness, such as weights initialization and data shuffling.

- **Parallelism**: The non-deterministic nature of GPU operations, especially with floating-point calculations, can lead to slight differences.

- **Environment**: Differences in software versions (PyTorch, CUDA, cuDNN), hardware, and operating systems can affect reproducibility

# Steps to Improve Reproducibility:
1. Use Random Seeds

In [21]:
import numpy as np
import random

SEED = 42
torch.manual_seed(SEED)
x = torch.rand(3,4)

torch.manual_seed(SEED)
y = torch.rand(3,4)

x,y, x==y

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [28]:
# Enable deterministic algorithms
torch.use_deterministic_algorithms(True)

# Set a seed for the random number generator for reproducibility
torch.manual_seed(42)

# Create a random tensor
x = torch.rand(3, 4)

# Print the tensor
print(x)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


`torch.use_deterministic_algorithms(True)` : This can help with reproducibility but may impact performance and may not cover all operations.